### PR TITLE
allow for making a shared library (Ref: #137)

### PR DESCRIPTION
**Pull request by AeroNotix**

### CODE REVIEW

**Comment by dtikhonov** [comment]
Hmm, that's it?  Did you also need to compile BoringSSL in shared mode?  (And are you using Linux?)

**Comment by AeroNotix** [comment]
Yes, documentation for doing this will need to be updated. Put this initial part out for feedback. The rest of the parts are just documentation updates.

**Comment by dtikhonov** [comment]
I tried your patch out, but I am having difficulties with BoringSSL.  Could you please specify how you configured and built BoringSSL?

**Comment by AeroNotix** [comment]
@dtikhonov I added instructions in the README for how I configured BoringSSL

**Comment by dtikhonov** [comment]
I made the branch [202009112252-shared-lib-test](https://github.com/litespeedtech/lsquic/tree/202009112252-shared-lib-test) and got the shared build working.

I don't see how you made it work without [this change](https://github.com/litespeedtech/lsquic/commit/5d5f5a7d09f87af1254d9da944678e16122669fd#diff-af3b638bc2a3e6c650974192a53c7291R157), though: did you forget to commit it?

**Comment by AeroNotix** [comment]
I did not forget to commit anything. I have been using the shared library built from this exact code for weeks. Is the implication that I would submit something that just outright did not work? I've literally been using the shared library built from this PR for weeks.

**Comment by dtikhonov** [comment]
Curious.  Well, it works for me with my changes -- I will merge your changes to master soon.  Thanks for the PR!

**Pull request merged**
